version: '3'
services:
  
  prisma:
    image: ${WEB_IMAGE}/{WEB_TAG}
    restart: always
    ports:
    - "${WEB_PORT}:4467"
    # - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4467
        # port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            #host: 192.168.99.100
            host: host.docker.internal
            #host: 127.0.0.1
            database: ${DbName}
            schema: public
            user: ${DbUser}
            #password: mysecretpassword
            password: ${DbPassword}
            ssl: false
            rawAccess: true
            port: ${DbPort}
            migrations: true
 