version: '3'
services:
  
  prisma:
    image: prismagraphql/prisma:1.31
    restart: always
    ports:
    - "4467:4467"
    # - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4467
        # port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            #host: 192.168.99.100
            host: host.docker.internal
            #host: 127.0.0.1
            database: centralauth
            schema: public
            user: postgres
            #password: mysecretpassword
            password: Sweet@18
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: true
 